### ISSUE TITLE
Panic in libp2p-kad

### ISSUE THREAD

**Issue by arkpar** [libp2p/rust-libp2p#1491]
Polkadot panics when running debug build after a while.

```
2020-03-11 03:44:04 Imported #1398447 (0x5bb8…4864)
2020-03-11 03:44:06 Polling the network future took 8.256043471s
2020-03-11 03:44:07 Idle (65 peers), best: #1398447 (0x39c1…b096), finalized #1398445 (0x5ea6…7b95), ⬇ 163.5kiB/s ⬆ 24.3kiB/s
2020-03-11 03:44:09 Imported #1398448 (0x9bf7…91d8)

====================

Version: 0.7.22-61e5d69e-x86_64-linux-gnu

stack backtrace:
   0: sp_panic_handler::panic_hook
             at /home/arkadiy/.cargo/git/checkouts/substrate-7e08433d4c370a21/a439a7a/primitives/panic-handler/src/lib.rs:148
   1: sp_panic_handler::set::{{closure}}
             at /home/arkadiy/.cargo/git/checkouts/substrate-7e08433d4c370a21/a439a7a/primitives/panic-handler/src/lib.rs:58
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   3: rust_begin_unwind
             at src/libstd/panicking.rs:375
   4: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
   5: core::panicking::panic
             at src/libcore/panicking.rs:51
   6: libp2p_kad::behaviour::Kademlia<TStore>::record_received::{{closure}}
             at /home/arkadiy/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-kad-0.16.2/src/behaviour.rs:947
   7: core::option::Option<T>::map
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/option.rs:450
   8: libp2p_kad::behaviour::Kademlia<TStore>::record_received
             at /home/arkadiy/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-kad-0.16.2/src/behaviour.rs:946
   9: <libp2p_kad::behaviour::Kademlia<TStore> as libp2p_swarm::behaviour::NetworkBehaviour>::inject_node_event
             at /home/arkadiy/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-kad-0.16.2/src/behaviour.rs:1295
  10: <sc_network::discovery::DiscoveryBehaviour as libp2p_swarm::behaviour::NetworkBehaviour>::inject_node_event
             at /home/arkadiy/.cargo/git/checkouts/substrate-7e08433d4c370a21/a439a7a/client/network/src/discovery.rs:290
  11: <sc_network::behaviour::Behaviour<B,H> as libp2p_swarm::behaviour::NetworkBehaviour>::inject_node_event
             at /home/arkadiy/.cargo/git/checkouts/substrate-7e08433d4c370a21/a439a7a/client/network/src/behaviour.rs:33
  12: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler,THandlerErr,TConnInfo>::poll_next_event
             at /home/arkadiy/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-swarm-0.16.1/src/lib.rs:355
  13: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler,THandlerErr,TConnInfo>::next_event::{{closure}}::{{closure}}
             at /home/arkadiy/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-swarm-0.16.1/src/lib.rs:324
  14: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/arkadiy/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/poll_fn.rs:54
  15: std::future::poll_with_tls_context
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/future.rs:99
  16: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler,THandlerErr,TConnInfo>::next_event::{{closure}}
             at /home/arkadiy/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-swarm-0.16.1/src/lib.rs:324
...

Thread 'main-tokio-' panicked at 'attempt to shift right with overflow', /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-kad-0.16.2/src/behaviour.rs:947

```

**Comment by mxinden** [comment]
From Riot:

> Ah, once `num_beyond_k` is `>=64` it overflows `ttl.as_secs()` which is a `u64`. As far as I can tell the overflow is very much by design, given that the expiration should exponentially decrease the further one is away from the target. If ones distance from the target is `>=64` it should expire immediately (`now + 0`).  I will prepare a patch.
