### ISSUE TITLE
Gossipsub error InsufficientPeers after publishing some messages.

### ISSUE THREAD

**Issue by Frederik-Baetens** [libp2p/rust-libp2p#2036]
This might be the same issue as #2034 

I have a repo to reproduce: https://github.com/Frederik-Baetens/libp2p-tokiochat

It has 2 branches, an "original" branch which more closely mirrors the tokio chat example and a more modified main branch which seems to show the error quicker. But both branches do show the same error eventually.

You can try it out by just cloning & running cargo run in 2 terminals just like with the libp2p examples.

example output I added some prints to show the peers being added and removed:

```
~/Programmeren/rust/tokiochat : cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.31s
     Running `target/debug/tokiochat`
Local peer id: PeerId("12D3KooWBaBPHkubfuFRqBowBs2t33VkMZpwt5zmYQTa5NetfT1a")
adding peer: PeerId("12D3KooWRSo7mSuk2RKhBryTiLr1m55tXMT6F9g55uodBAHLVGVc")
...
adding peer: PeerId("12D3KooWRSo7mSuk2RKhBryTiLr1m55tXMT6F9g55uodBAHLVGVc")
Listening on "/ip4/192.168.122.1/tcp/36323"
Listening on "/ip4/127.0.0.1/tcp/36323"
Listening on "/ip4/192.168.1.105/tcp/36323"
Listening on "/ip4/172.17.0.1/tcp/36323"
adding peer: PeerId("12D3KooWRSo7mSuk2RKhBryTiLr1m55tXMT6F9g55uodBAHLVGVc")
...
adding peer: PeerId("12D3KooWRSo7mSuk2RKhBryTiLr1m55tXMT6F9g55uodBAHLVGVc")
lkdfj
mdlfj
dmsqlfkj
dmqlfkjs
jdfls
lsdjfjsdflm
dmsflkjdfjmjfd
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: InsufficientPeers', src/main.rs:218:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Sometimes I also get no error output, and it just exists without printing anything (on the main branch, haven't experimented as much on the original branch)

Also, is it normal that the same peer gets added multiple times?

**Comment by Frederik-Baetens** [comment]
There's also a branch [no_mdns](https://github.com/Frederik-Baetens/libp2p-tokiochat/tree/no_mdns) which shows this happening without any mdns network behaviour.

**Comment by Frederik-Baetens** [comment]
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: InsufficientPeers', src/main.rs:209:59
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: core::result::Result<T,E>::unwrap
             at /home/frederik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1037:23
   4: tokiochat::run::{{closure}}
             at ./main.rs:209:13
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/frederik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   6: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/task/core.rs:235:17
   7: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/loom/std/unsafe_cell.rs:14:9
   8: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/task/core.rs:225:13
   9: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/task/harness.rs:422:23
  10: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/frederik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  11: std::panicking::try::do_call
             at /home/frederik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  12: __rust_try
  13: std::panicking::try
             at /home/frederik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  14: std::panic::catch_unwind
             at /home/frederik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  15: tokio::runtime::task::harness::poll_future
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/task/harness.rs:409:19
  16: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/task/harness.rs:89:9
  17: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/task/harness.rs:59:15
  18: tokio::runtime::task::raw::poll
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/task/raw.rs:104:5
  19: tokio::runtime::task::raw::RawTask::poll
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/task/raw.rs:66:18
  20: tokio::runtime::task::Notified<S>::run
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/task/mod.rs:171:9
  21: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/thread_pool/worker.rs:349:13
  22: tokio::coop::with_budget::{{closure}}
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/coop.rs:121:9
  23: std::thread::local::LocalKey<T>::try_with
             at /home/frederik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  24: std::thread::local::LocalKey<T>::with
             at /home/frederik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  25: tokio::coop::with_budget
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/coop.rs:114:5
  26: tokio::coop::budget
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/coop.rs:98:5
  27: tokio::runtime::thread_pool::worker::Context::run_task
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/thread_pool/worker.rs:348:9
  28: tokio::runtime::thread_pool::worker::Context::run
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/thread_pool/worker.rs:318:24
  29: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/thread_pool/worker.rs:303:17
  30: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/macros/scoped_tls.rs:61:9
  31: tokio::runtime::thread_pool::worker::run
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/thread_pool/worker.rs:300:5
  32: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/thread_pool/worker.rs:279:45
  33: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/blocking/task.rs:42:21
  34: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/task/core.rs:235:17
  35: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/loom/std/unsafe_cell.rs:14:9
  36: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/task/core.rs:225:13
  37: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/task/harness.rs:422:23
  38: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/frederik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  39: std::panicking::try::do_call
             at /home/frederik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  40: __rust_try
  41: std::panicking::try
             at /home/frederik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  42: std::panic::catch_unwind
             at /home/frederik/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  43: tokio::runtime::task::harness::poll_future
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/task/harness.rs:409:19
  44: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/task/harness.rs:89:9
  45: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/task/harness.rs:59:15
  46: tokio::runtime::task::raw::poll
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/task/raw.rs:104:5
  47: tokio::runtime::task::raw::RawTask::poll
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/task/raw.rs:66:18
  48: tokio::runtime::task::Notified<S>::run
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/task/mod.rs:171:9
  49: tokio::runtime::blocking::pool::Inner::run
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/blocking/pool.rs:278:17
  50: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/frederik/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/blocking/pool.rs:258:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Stack trace, should it be helpful

**Comment by AgeManning** [comment]
This does appear to be the same as #2034. 

Could you please try: https://github.com/libp2p/rust-libp2p/pull/2043 and see if this resolves your issue.

**Comment by Frederik-Baetens** [comment]
Seems to fix it, thanks for the really quick fix!
