### ISSUE TITLE
Rendezvous panics on wasm32 arch

### ISSUE THREAD

**Issue by sireliah** [libp2p/rust-libp2p#2399]
Hi, I'm developing browser wasm32 application that uses rendezvous over websockets transport. I have noticed that instantiating swarm with rendezvous behaviour and polling events from the swarm results in panic:

```
panicked at 'time not implemented on this platform', library/std/src/sys/wasm/../unsupported/time.rs:39:9
```

<details>
  <summary>Full stacktrace</summary>

  ```
panicked at 'time not implemented on this platform', library/std/src/sys/wasm/../unsupported/time.rs:39:9

Stack:

init/imports.wbg.__wbg_new_693216e109162396@http://localhost:8080/hello.js:320:19
@http://localhost:8080/hello_bg.wasm:wasm-function[672]:0xe0011
@http://localhost:8080/hello_bg.wasm:wasm-function[1914]:0x10dfdd
@http://localhost:8080/hello_bg.wasm:wasm-function[1051]:0xfd3fe
@http://localhost:8080/hello_bg.wasm:wasm-function[1639]:0x10ca99
@http://localhost:8080/hello_bg.wasm:wasm-function[1593]:0x10c2d3
@http://localhost:8080/hello_bg.wasm:wasm-function[1638]:0x10ca6c
@http://localhost:8080/hello_bg.wasm:wasm-function[188]:0x804d4
@http://localhost:8080/hello_bg.wasm:wasm-function[470]:0xc5fac
@http://localhost:8080/hello_bg.wasm:wasm-function[90]:0x27f4b
@http://localhost:8080/hello_bg.wasm:wasm-function[125]:0x587c8
@http://localhost:8080/hello_bg.wasm:wasm-function[975]:0xf8e33
@http://localhost:8080/hello_bg.wasm:wasm-function[885]:0xf2e45
@http://localhost:8080/hello_bg.wasm:wasm-function[1684]:0x10d0c9
__wbg_adapter_26@http://localhost:8080/hello.js:207:10
real@http://localhost:8080/hello.js:192:20
promise callback*init/imports.wbg.__wbg_then_2fcac196782070cc@http://localhost:8080/hello.js:592:35
@http://localhost:8080/hello_bg.wasm:wasm-function[1019]:0xfb783
@http://localhost:8080/hello_bg.wasm:wasm-function[956]:0xf7b71
@http://localhost:8080/hello_bg.wasm:wasm-function[1463]:0x10a5e6
@http://localhost:8080/hello_bg.wasm:wasm-function[916]:0xf51a4
@http://localhost:8080/hello_bg.wasm:wasm-function[1463]:0x10a5e6
@http://localhost:8080/hello_bg.wasm:wasm-function[916]:0xf51a4
@http://localhost:8080/hello_bg.wasm:wasm-function[843]:0xefb19
@http://localhost:8080/hello_bg.wasm:wasm-function[1444]:0x109fee
@http://localhost:8080/hello_bg.wasm:wasm-function[1684]:0x10d0c9
__wbg_adapter_26@http://localhost:8080/hello.js:207:10
real@http://localhost:8080/hello.js:192:20
promise callback*init/imports.wbg.__wbg_then_8c2d62e8ae5978f7@http://localhost:8080/hello.js:596:35
@http://localhost:8080/hello_bg.wasm:wasm-function[509]:0xcbeb5
@http://localhost:8080/hello_bg.wasm:wasm-function[421]:0xbe347
@http://localhost:8080/hello_bg.wasm:wasm-function[245]:0x94d3c
@http://localhost:8080/hello_bg.wasm:wasm-function[1076]:0xfe815
@http://localhost:8080/hello_bg.wasm:wasm-function[864]:0xf1547
@http://localhost:8080/hello_bg.wasm:wasm-function[204]:0x86860
@http://localhost:8080/hello_bg.wasm:wasm-function[225]:0x8e281
@http://localhost:8080/hello_bg.wasm:wasm-function[569]:0xd3fbd
@http://localhost:8080/hello_bg.wasm:wasm-function[485]:0xc845a
@http://localhost:8080/hello_bg.wasm:wasm-function[136]:0x62026
@http://localhost:8080/hello_bg.wasm:wasm-function[222]:0x8d00d
@http://localhost:8080/hello_bg.wasm:wasm-function[239]:0x92986
@http://localhost:8080/hello_bg.wasm:wasm-function[775]:0xe9da7
@http://localhost:8080/hello_bg.wasm:wasm-function[1818]:0x10db45
@http://localhost:8080/hello_bg.wasm:wasm-function[824]:0xee14e
@http://localhost:8080/hello_bg.wasm:wasm-function[280]:0x9ef79
@http://localhost:8080/hello_bg.wasm:wasm-function[401]:0xba704
@http://localhost:8080/hello_bg.wasm:wasm-function[428]:0xbf614
@http://localhost:8080/hello_bg.wasm:wasm-function[277]:0x9e2d4
@http://localhost:8080/hello_bg.wasm:wasm-function[291]:0xa1e67
@http://localhost:8080/hello_bg.wasm:wasm-function[95]:0x31db4
@http://localhost:8080/hello_bg.wasm:wasm-function[303]:0xa5019
@http://localhost:8080/hello_bg.wasm:wasm-function[90]:0x269fa
@http://localhost:8080/hello_bg.wasm:wasm-function[125]:0x587c8
@http://localhost:8080/hello_bg.wasm:wasm-function[975]:0xf8e33
@http://localhost:8080/hello_bg.wasm:wasm-function[885]:0xf2e45
@http://localhost:8080/hello_bg.wasm:wasm-function[1684]:0x10d0c9
__wbg_adapter_26@http://localhost:8080/hello.js:207:10
real@http://localhost:8080/hello.js:192:20


hello.js:332:21
    __wbg_error_09919627ac0992f5 http://localhost:8080/hello.js:332
    <anonymous> http://localhost:8080/hello_bg.wasm:917734
    <anonymous> http://localhost:8080/hello_bg.wasm:1105885
    <anonymous> http://localhost:8080/hello_bg.wasm:1037310
    <anonymous> http://localhost:8080/hello_bg.wasm:1100441
    <anonymous> http://localhost:8080/hello_bg.wasm:1098451
    <anonymous> http://localhost:8080/hello_bg.wasm:1100396
    <anonymous> http://localhost:8080/hello_bg.wasm:525524
    <anonymous> http://localhost:8080/hello_bg.wasm:810924
    <anonymous> http://localhost:8080/hello_bg.wasm:163659
    <anonymous> http://localhost:8080/hello_bg.wasm:362440
    <anonymous> http://localhost:8080/hello_bg.wasm:1019443
    <anonymous> http://localhost:8080/hello_bg.wasm:994885
    <anonymous> http://localhost:8080/hello_bg.wasm:1102025
    __wbg_adapter_26 http://localhost:8080/hello.js:207
    real http://localhost:8080/hello.js:192
    (Async: promise callback)
    __wbg_then_2fcac196782070cc http://localhost:8080/hello.js:592
    <anonymous> http://localhost:8080/hello_bg.wasm:1030019
    <anonymous> http://localhost:8080/hello_bg.wasm:1014641
    <anonymous> http://localhost:8080/hello_bg.wasm:1091046
    <anonymous> http://localhost:8080/hello_bg.wasm:1003940
    <anonymous> http://localhost:8080/hello_bg.wasm:1091046
    <anonymous> http://localhost:8080/hello_bg.wasm:1003940
    <anonymous> http://localhost:8080/hello_bg.wasm:981785
    <anonymous> http://localhost:8080/hello_bg.wasm:1089518
    <anonymous> http://localhost:8080/hello_bg.wasm:1102025
    __wbg_adapter_26 http://localhost:8080/hello.js:207
    real http://localhost:8080/hello.js:192
    (Async: promise callback)
    __wbg_then_8c2d62e8ae5978f7 http://localhost:8080/hello.js:596
    <anonymous> http://localhost:8080/hello_bg.wasm:835253
    <anonymous> http://localhost:8080/hello_bg.wasm:779079
    <anonymous> http://localhost:8080/hello_bg.wasm:609596
    <anonymous> http://localhost:8080/hello_bg.wasm:1042453
    <anonymous> http://localhost:8080/hello_bg.wasm:988487
    <anonymous> http://localhost:8080/hello_bg.wasm:551008
    <anonymous> http://localhost:8080/hello_bg.wasm:582273
    <anonymous> http://localhost:8080/hello_bg.wasm:868285
    <anonymous> http://localhost:8080/hello_bg.wasm:820314
    <anonymous> http://localhost:8080/hello_bg.wasm:401446
    <anonymous> http://localhost:8080/hello_bg.wasm:577549
    <anonymous> http://localhost:8080/hello_bg.wasm:600454
    <anonymous> http://localhost:8080/hello_bg.wasm:957863
    <anonymous> http://localhost:8080/hello_bg.wasm:1104709
    <anonymous> http://localhost:8080/hello_bg.wasm:975182
    <anonymous> http://localhost:8080/hello_bg.wasm:651129
    <anonymous> http://localhost:8080/hello_bg.wasm:763652
    <anonymous> http://localhost:8080/hello_bg.wasm:783892
    <anonymous> http://localhost:8080/hello_bg.wasm:647892
    <anonymous> http://localhost:8080/hello_bg.wasm:663143
    <anonymous> http://localhost:8080/hello_bg.wasm:204212
    <anonymous> http://localhost:8080/hello_bg.wasm:675865
    <anonymous> http://localhost:8080/hello_bg.wasm:158202
    <anonymous> http://localhost:8080/hello_bg.wasm:362440
    <anonymous> http://localhost:8080/hello_bg.wasm:1019443
    <anonymous> http://localhost:8080/hello_bg.wasm:994885
    <anonymous> http://localhost:8080/hello_bg.wasm:1102025
    __wbg_adapter_26 http://localhost:8080/hello.js:207
    real http://localhost:8080/hello.js:192
```

</details>

Related deps:

```toml
[target.'cfg(target_arch = "wasm32")'.dependencies]
async-datachannel-wasm = "0.1.2"
futures = "0.3.17"
futures-macro = "0.3.17"
futures-timer = { version = "3.0.2", features = ["wasm-bindgen"] }
send_wrapper = { version = "0.5.0", features = ["futures"] }
libp2p = { version = "0.41.0", features = ["wasm-bindgen", "wasm-ext", "websocket", "wasm-ext-websocket", "mplex", "noise", "ping", "rendezvous"], default_features = false }
ws_stream_wasm = "0.7.3"
wasm-bindgen-futures = "0.4.28"
```

Browser: Firefox 94.0

[Gist with the code](https://gist.github.com/sireliah/2d5924e65ed71d62c9acad2ccd516793) I'm running in the browser. Watch out, it's a messy WIP version.

Now, through some careful debugging I've found out that the reason of the error is the usage of `std::time::Duration` [here](
https://github.com/libp2p/rust-libp2p/blob/master/protocols/rendezvous/src/client.rs#L40). Wasm cannot measure time the same way as different architectures. 

Replacing `std::time::Duration` with `instant::Duration` fixes the issue.

Question is: is it fine to use the `instant` there? If it's fine, I'll open a PR with the fix.

**Comment by thomaseizinger** [comment]
> Question is: is it fine to use the `instant` there? If it's fine, I'll open a PR with the fix.

Yep that is fine and actually much appreciated!

We strive to support running protocols in WASM where it makes sense. This is merely just an oversight, sorry about that!
