### ISSUE TITLE
TLS server cert key error in libp2p-core 0.41.3

### ISSUE THREAD

**Issue by cargodog** [libp2p/rust-libp2p#5497]
### Summary

Since libp2p-core upgraded to 0.41.3, attempting to start a swarm with a TCP listener results in immediate panic.

The issue has to do with using libp2p with latest `rustls` dependency (recently upgraded from `0.23.9` to `0.23.11`). This is applicable to projects which perform a clean build with no `Cargo.lock` or lock set to `libp2p-core@0.41.3`.

## Steps to reproduce
This can be reproduced in the chat example app by updating the rustls dependency and running.

1) Update rustls
first, upgrade rustls:
```cargo update rustls@0.23.9```
OR update everything:
```cargo update```
OR just pretend this is a new build without a lock file:
```rm Cargo.lock```

2) Run chat example
```cargo run --bin chat-example```

### Expected behavior

Swarm should start listener without error.

### Actual behavior

Swarm causes panic with the following message:
```
Server cert key DER is valid; qed: InvalidCertificate(Other(OtherError(UnsupportedCriticalExtension)))
```

### Relevant log output

```shell
$ RUST_BACKTRACE=1 cargo run --bin chat-example
warning: struct `Ping` is never constructed
  --> protocols/ping/src/protocol.rs:48:19
   |
48 | pub(crate) struct Ping;
   |                   ^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `libp2p-ping` (lib) generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.34s
     Running `target/debug/chat-example`
thread 'main' panicked at transports/tls/src/lib.rs:80:10:
Server cert key DER is valid; qed: InvalidCertificate(Other(OtherError(UnsupportedCriticalExtension)))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c6727fc9b5c64cefa7263486497ee95e529bd0f8/library/std/src/panicking.rs:661:5
   1: core::panicking::panic_fmt
             at /rustc/c6727fc9b5c64cefa7263486497ee95e529bd0f8/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/c6727fc9b5c64cefa7263486497ee95e529bd0f8/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::expect
             at /rustc/c6727fc9b5c64cefa7263486497ee95e529bd0f8/library/core/src/result.rs:1059:23
   4: libp2p_tls::make_server_config
             at ./transports/tls/src/lib.rs:75:22
   5: libp2p_quic::config::Config::new
             at ./transports/quic/src/config.rs:82:40
   6: libp2p::builder::phase::quic::<impl libp2p::builder::SwarmBuilder<libp2p::builder::phase::provider::Tokio,libp2p::builder::phase::quic::QuicPhase<T>>>::with_quic_config
             at ./libp2p/src/builder/phase/quic.rs:44:37
   7: libp2p::builder::phase::quic::<impl libp2p::builder::SwarmBuilder<libp2p::builder::phase::provider::Tokio,libp2p::builder::phase::quic::QuicPhase<T>>>::with_quic
             at ./libp2p/src/builder/phase/quic.rs:27:17
   8: chat_example::main::{{closure}}
             at ./examples/chat/src/main.rs:45:21
   9: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:63
  10: tokio::runtime::coop::with_budget
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:107:5
  11: tokio::runtime::coop::budget
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:73:5
  12: tokio::runtime::park::CachedParkThread::block_on
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:31
  13: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/blocking.rs:66:9
  14: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  15: tokio::runtime::context::runtime::enter_runtime
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:65:16
  16: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  17: tokio::runtime::runtime::Runtime::block_on
             at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/runtime.rs:349:45
  18: chat_example::main
             at ./examples/chat/src/main.rs:97:5
  19: core::ops::function::FnOnce::call_once
             at /rustc/c6727fc9b5c64cefa7263486497ee95e529bd0f8/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Version

This appears in `libp2p 0.53.2` specifically with `libp2p-core 0.41.3`

### Would you like to work on fixing this bug ?

Maybe

**Comment by cargodog** [comment]
Its possible this has nothing to do with libp2p and rustls accidentally introduced a breaking change or bug in their latest patch, but I can't say that for sure yet. Depending on my availability, I will try to check back tomorrow and get a clearer understanding of the root cause.

**Comment by cargodog** [comment]
oops, this is a duplicate issue. Closing.

original issue here: https://github.com/libp2p/rust-libp2p/issues/5487
