### ISSUE TITLE
After upgrading to macOS 15 (macOS Sequoia) beta3, using quic will cause p2p startup failure

### ISSUE THREAD

**Issue by RustLoverTheCoder** [libp2p/rust-libp2p#5500]
### Summary

After upgrading to macOS 15 (macOS Sequoia) beta3, the p2p node cannot be started correctly.

### Expected behavior

p2p start

### Actual behavior

Error message:

```bash
2024-07-15T08:18:23.235928Z DEBUG p2p::node: local identity: Keypair {
    keypair: Ed25519(
        Keypair {
            public: VerifyingKey(CompressedEdwardsY: [66, 157, 115, 94, 88, 91, 128, 120, 201, 240, 177, 184, 167, 78, 206, 7, 233, 53, 209, 146, 215, 24, 204, 209, 92, 100, 93, 16, 202, 216, 155, 136]), EdwardsPoint{
                X: FieldElement51([1746077081254800, 299169106966165, 34027628916236, 952123496437776, 2112824036115580]),
                Y: FieldElement51([1365216460372505, 2166694543252363, 1909125290940808, 888049894977144, 2154226495488740]),
                Z: FieldElement51([429647743373819, 1211574908664842, 985354025980357, 350114512567971, 936422014365698]),
                T: FieldElement51([126001234603738, 1315702523752148, 1039256951771276, 1040160480904130, 1935148284231361])
            }),
        },
    ),
}
2024-07-15T08:18:23.236238Z  INFO p2p::node: local peer_id: PeerId(
    "12D3KooWEJQKvMmcxGr5ZWWabJoH1m4hDNbiNFzfYuUkzpKKQ3mH",
)
thread 'main' panicked at /Users/zhuo/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/libp2p-tls-0.4.0/src/lib.rs:80:10:
Server cert key DER is valid; qed: InvalidCertificate(Other(OtherError(UnsupportedCriticalExtension)))
```

### Relevant log output

```shell
2024-07-15T08:18:23.235928Z DEBUG p2p::node: local identity: Keypair {
    keypair: Ed25519(
        Keypair {
            public: VerifyingKey(CompressedEdwardsY: [66, 157, 115, 94, 88, 91, 128, 120, 201, 240, 177, 184, 167, 78, 206, 7, 233, 53, 209, 146, 215, 24, 204, 209, 92, 100, 93, 16, 202, 216, 155, 136]), EdwardsPoint{
                X: FieldElement51([1746077081254800, 299169106966165, 34027628916236, 952123496437776, 2112824036115580]),
                Y: FieldElement51([1365216460372505, 2166694543252363, 1909125290940808, 888049894977144, 2154226495488740]),
                Z: FieldElement51([429647743373819, 1211574908664842, 985354025980357, 350114512567971, 936422014365698]),
                T: FieldElement51([126001234603738, 1315702523752148, 1039256951771276, 1040160480904130, 1935148284231361])
            }),
        },
    ),
}
2024-07-15T08:18:23.236238Z  INFO p2p::node: local peer_id: PeerId(
    "12D3KooWEJQKvMmcxGr5ZWWabJoH1m4hDNbiNFzfYuUkzpKKQ3mH",
)
thread 'main' panicked at /Users/zhuo/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/libp2p-tls-0.4.0/src/lib.rs:80:10:
Server cert key DER is valid; qed: InvalidCertificate(Other(OtherError(UnsupportedCriticalExtension)))
```

### Possible Solution

tcp and quic should conflict and only one should be used

### Would you like to work on fixing this bug ?

Yes

**Comment by elecbug** [comment]
Well, there is code information in the original text, and it would be better to register the code information in an issue together. The original text seems to be in Chinese characters, but it's hard to read them.

I think it's a story that using the Quic part commented in the code below will cause problems, right?

```rs
// crates/p2p/src/swarm.rs

...


pub fn build_swarm(
    identity: Keypair,
    metadata: HashMap<String, String>,
) -> Result<Swarm<Behaviour>, P2PError<()>> {
    Ok(libp2p::SwarmBuilder::with_existing_identity(identity)
        .with_tokio()
        .with_tcp(
            tcp::Config::default(),
            noise::Config::new,
            yamux::Config::default,
        )?
        // .with_quic()
        .with_relay_client(noise::Config::new, yamux::Config::default)?
        .with_behaviour(|key, relay_behaviour| {
            Behaviour::new(key.public(), relay_behaviour, metadata)
        })?
        .with_swarm_config(|cfg| cfg.with_idle_connection_timeout(Duration::from_secs(u64::MAX)))
        .build())
}
```

**Comment by romac** [comment]
This is likely the same issue as https://github.com/libp2p/rust-libp2p/issues/5487

**Comment by RustLoverTheCoder** [comment]
@romac Yes, I think the certificate caused the error

**Comment by RustLoverTheCoder** [comment]
@elecbug Using quic will cause startup failure
