### ISSUE TITLE
thread 'main' panicked at libp2p-relay-0.17.2/src/priv_client/transport.rs:237

### ISSUE THREAD

**Issue by lynic** [libp2p/rust-libp2p#5502]
### Summary

I'm trying to write a libp2p client and let it create to a relay server, I enabled dcutr and relay and gossibsub and kad.

Somehow it panicked, would like to request help to debug it.

### Expected behavior

not panic

### Actual behavior

panic

### Relevant log output

```shell
Told relay its public address
Relay told us our observed address /ip4/219.78.226.76/tcp/46840
dialed to relay server
start listening on relay address /dns/vps5.xxxxxx.net/tcp/8443/p2p/12D3KooWHThNsD8z3ahmG5ihYbz3zSYtUHqLY1YiChTrZFVFZpjd/p2p-circuit
...
event: NewExternalAddrCandidate { address: "/ip4/219.78.226.76/tcp/42717" }
thread 'main' panicked at /home/vagrant/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libp2p-relay-0.17.2/src/priv_client/transport.rs:237:44:
internal error: entered unreachable code: Receiver is never dropped.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```


### Possible Solution

_No response_

### Version

_No response_

### Would you like to work on fixing this bug ?

No

**Comment by jxs** [comment]
Hi, and thanks for the interest, do you have a reproducible case for aforementioned `panic`?

**Comment by lynic** [comment]
I'm not sure if it's related to using tokio in relay server, as in example it's using async_std.
Have anyone use tokio for relay server?

**Comment by dariusc93** [comment]
Could you provide any code that you may be using for your relay server? I dont have an issue with the example or my own code so just curious is all. It shouldnt matter if youre using async-std or tokio though
