### ISSUE TITLE
Panic in Kademlia

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#986]
```
2019-02-28 16:38:58 connection error: decode error: i/o error: I/O error: Connection reset by peer (os error 104)
2019-02-28 16:38:58 Idle (0 peers), best: #1181 (0x7d4f…e5bd), finalized #1062 (0x1c5d…819c), ⬇ 4.1kiB/s ⬆ 4.2kiB/s
2019-02-28 16:38:59 connection error: decode error: i/o error: I/O error: Connection reset by peer (os error 104)
2019-02-28 16:39:03 Idle (0 peers), best: #1181 (0x7d4f…e5bd), finalized #1062 (0x1c5d…819c), ⬇ 3.9kiB/s ⬆ 4.3kiB/s

====================

stack backtrace:
   0: substrate_panic_handler::panic_hook::hf62058ec7170ccff (0x564c21c02a2d)
             at core/panic-handler/src/lib.rs:82
   1: substrate_panic_handler::set::{{closure}}::h4fa84d9849a2f949 (0x564c21c03876)
             at core/panic-handler/src/lib.rs:31
   2: rust_panic_with_hook (0x564c2205d28d)
             at src/libstd/panicking.rs:482
   3: std::panicking::begin_panic::hd57a09ec332f8f8a (0x564c21db1f17)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/panicking.rs:412
   4: <libp2p_kad::behaviour::Kademlia<TSubstream> as libp2p_core::swarm::NetworkBehaviour>::inject_disconnected::hb1e488f975396354 (0x564c1fdf898e)
             at /home/davidd/parity_ltd/gitlab/substrate/<::std::macros::panic macros>:3
   5: <substrate_network_libp2p::behaviour::DiscoveryBehaviour<TSubstream> as libp2p_core::swarm::NetworkBehaviour>::inject_disconnected::h156faa7fe54db198 (0x564c1fd102c3)
             at /home/davidd/parity_ltd/gitlab/substrate/core/network-libp2p/src/behaviour.rs:348
   6: <substrate_network_libp2p::behaviour::Behaviour<TMessage, TSubstream> as libp2p_core::swarm::NetworkBehaviour>::inject_disconnected::h2cdf612e539b49e0 (0x564c1fd11e4c)
             at /home/davidd/parity_ltd/gitlab/substrate/core/network-libp2p/src/behaviour.rs:34
   7: <libp2p_core::swarm::Swarm<TTransport, TBehaviour> as futures::stream::Stream>::poll::hdeabed9cc9bc268b (0x564c1faacece)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.4.0/src/swarm.rs:265
   8: <substrate_network_libp2p::service_task::Service<TMessage>>::poll_swarm::h5cfac103685c6a9b (0x564c1fb1f1c0)
             at /home/davidd/parity_ltd/gitlab/substrate/core/network-libp2p/src/service_task.rs:383
   9: <substrate_network_libp2p::service_task::Service<TMessage> as futures::stream::Stream>::poll::h36771ecadd533236 (0x564c1fb1b6ec)
             at /home/davidd/parity_ltd/gitlab/substrate/core/network-libp2p/src/service_task.rs:481
  10: substrate_network::service::run_thread::{{closure}}::hb61a91cfcee0354a (0x564c1f32dc4e)
             at /home/davidd/parity_ltd/gitlab/substrate/core/network/src/service.rs:529
  11: <futures::stream::poll_fn::PollFn<F> as futures::stream::Stream>::poll::h69ea38ae535d02e3 (0x564c2000b7da)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/stream/poll_fn.rs:47
  12: <futures::stream::for_each::ForEach<S, F, U> as futures::future::Future>::poll::h24299377870d6275 (0x564c1f3331bf)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/stream/for_each.rs:45
  13: <alloc::boxed::Box<F> as futures::future::Future>::poll::h5cd6604b9d0022ce (0x564c200cda4b)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/mod.rs:113
  14: <futures::future::select_all::SelectAll<A> as futures::future::Future>::poll::{{closure}}::ha22287c299368090 (0x564c1fa94c89)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/select_all.rs:53
  15: <core::iter::adapters::FilterMap<I, F> as core::iter::traits::iterator::Iterator>::next::h976c5af6a34d898b (0x564c1fcc6e65)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libcore/iter/adapters/mod.rs:823
  16: <futures::future::select_all::SelectAll<A> as futures::future::Future>::poll::ha0cf01e70085adbc (0x564c1fa9469d)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/select_all.rs:52
  17: <futures::future::chain::Chain<A, B, C>>::poll::h16d498498f57747a (0x564c2023c47c)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/chain.rs:26
  18: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::h5ca2510e54e2229e (0x564c1ffe14aa)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/and_then.rs:32
  19: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::h484c0340d7787890 (0x564c1f750e23)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/map_err.rs:30
  20: <futures::future::select::Select<A, B> as futures::future::Future>::poll::hf1e08867cf691a37 (0x564c1faa162e)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/select.rs:48
  21: <futures::future::map::Map<A, F> as futures::future::Future>::poll::he6b0a9c17951a64c (0x564c1f73979e)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/map.rs:30
  22: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::h86cdb985c1937353 (0x564c1f754286)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/map_err.rs:30
  23: <futures::future::chain::Chain<A, B, C>>::poll::hc71e98cc3c599e29 (0x564c2024d272)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/chain.rs:26
  24: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll::h7e15319852277a09 (0x564c1fdfece3)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/then.rs:32
  25: <alloc::boxed::Box<F> as futures::future::Future>::poll::h07c40b15cac3b6af (0x564c21b3f684)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/mod.rs:113
  26: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}::h6e99a6de4f742c0f (0x564c21a6f663)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:326
  27: <futures::task_impl::Spawn<T>>::enter::{{closure}}::hd5a11db7d208f674 (0x564c21a6f940)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:396
  28: futures::task_impl::std::set::hd08943674cd4509f (0x564c21a83666)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/std/mod.rs:78
  29: <futures::task_impl::Spawn<T>>::enter::h56fa649139884eb4 (0x564c21a6f78e)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:396
  30: <futures::task_impl::Spawn<T>>::poll_fn_notify::hef33673527356607 (0x564c21a6f4f7)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:288
  31: <futures::task_impl::Spawn<T>>::poll_future_notify::hb4f01b9d464fd068 (0x564c21a6f637)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:326
  32: tokio_threadpool::task::Task::run::{{closure}}::h1a5249888e3d7779 (0x564c21a7ab11)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/task/mod.rs:141
  33: core::ops::function::FnOnce::call_once::hdc67c1a9169e38d3 (0x564c21a6fdc8)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libcore/ops/function.rs:231
  34: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h8fc6d85e064b88e9 (0x564c21a6cc97)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/panic.rs:309
  35: std::panicking::try::do_call::h47aea246ce979ca8 (0x564c21a6ed12)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/panicking.rs:297
  36: __rust_maybe_catch_panic (0x564c22063139)
             at src/libpanic_unwind/lib.rs:92
  37: std::panicking::try::hd592460f4d45f52e (0x564c21a6eb7f)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/panicking.rs:276
  38: std::panic::catch_unwind::h85d6b58aeece480d (0x564c21a6e9c0)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/panic.rs:388
  39: tokio_threadpool::task::Task::run::h909535604bfdec5d (0x564c21a7a545)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/task/mod.rs:127
  40: tokio_threadpool::worker::Worker::run_task2::h54837e4e909858ed (0x564c21ab0cce)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/worker/mod.rs:572
  41: tokio_threadpool::worker::Worker::run_task::h3bb4a1c34d3fb4f6 (0x564c21ab0593)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/worker/mod.rs:461
  42: tokio_threadpool::worker::Worker::try_run_owned_task::h13ed79efe8d9fc5c (0x564c21aafc3f)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/worker/mod.rs:394
  43: tokio_threadpool::worker::Worker::try_run_task::h52ec07f144fb9610 (0x564c21aaf65c)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/worker/mod.rs:302
  44: tokio_threadpool::worker::Worker::run::h34dbe1ad6be21a40 (0x564c21aaf4b5)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/worker/mod.rs:246
  45: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::he1e47844b02e0b2f (0x564c21a23a2b)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.15/src/runtime/threadpool/builder.rs:340
  46: tokio_timer::timer::handle::with_default::{{closure}}::h0ee1978fe1542c12 (0x564c21a23e9d)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/timer/handle.rs:94
  47: <std::thread::local::LocalKey<T>>::try_with::hb28efc23c9f0e997 (0x564c21a25476)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/thread/local.rs:296
  48: <std::thread::local::LocalKey<T>>::with::h82f587cf590e5aa4 (0x564c21a24d42)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/thread/local.rs:242
  49: tokio_timer::timer::handle::with_default::h5c67ac04cc34431f (0x564c21a23ce2)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/timer/handle.rs:81
  50: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::h9d758111b2b9dedc (0x564c21a23a8b)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.15/src/runtime/threadpool/builder.rs:339
  51: tokio_timer::clock::clock::with_default::{{closure}}::hc601478651456460 (0x564c21a2e250)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/clock/clock.rs:141
  52: <std::thread::local::LocalKey<T>>::try_with::h71b69b7a5ea9149c (0x564c21a2521b)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/thread/local.rs:296
  53: <std::thread::local::LocalKey<T>>::with::h3cf687fa4b8f7cc1 (0x564c21a24c4c)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/thread/local.rs:242
  54: tokio_timer::clock::clock::with_default::h43d7a47915450f40 (0x564c21a2e13d)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/clock/clock.rs:124
  55: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::h52d36d7c86ca0f9b (0x564c21a23adc)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.15/src/runtime/threadpool/builder.rs:338
  56: tokio_reactor::with_default::{{closure}}::hbfccb4966f20b11b (0x564c21a2424e)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.8/src/lib.rs:229
  57: <std::thread::local::LocalKey<T>>::try_with::hcb00c150a80f35bc (0x564c21a256e2)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/thread/local.rs:296
  58: <std::thread::local::LocalKey<T>>::with::h81266653a23fdf09 (0x564c21a24ccc)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/thread/local.rs:242
  59: tokio_reactor::with_default::hdbee017b80624950 (0x564c21a24014)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.8/src/lib.rs:212
  60: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h4a45980098a20c82 (0x564c21a23b7f)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.15/src/runtime/threadpool/builder.rs:337
  61: tokio_threadpool::callback::Callback::call::hfce989d64409c27d (0x564c21a9af62)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/callback.rs:21
  62: tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}::h9703a9b47bfe88ee (0x564c21aaf14e)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/worker/mod.rs:132
  63: tokio_executor::global::with_default::{{closure}}::h7d0121fd86d679ea (0x564c21ab250a)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.6/src/global.rs:192
  64: <std::thread::local::LocalKey<T>>::try_with::h100f365f31d3fba2 (0x564c21a76e8f)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/thread/local.rs:296
  65: <std::thread::local::LocalKey<T>>::with::h40ba85c5071b8236 (0x564c21a76b32)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/thread/local.rs:242
  66: tokio_executor::global::with_default::h0b78e532a4f4c364 (0x564c21ab23e5)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.6/src/global.rs:162
  67: tokio_threadpool::worker::Worker::do_run::{{closure}}::h2597d9e803263fe3 (0x564c21aaf1fc)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/worker/mod.rs:130
  68: <std::thread::local::LocalKey<T>>::try_with::ha6adda9329fb0d51 (0x564c21a77a69)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/thread/local.rs:296
  69: <std::thread::local::LocalKey<T>>::with::hba20195978052efd (0x564c21a76b9d)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/thread/local.rs:242
  70: tokio_threadpool::worker::Worker::do_run::h5be1e53165ed025b (0x564c21aaf027)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/worker/mod.rs:121
  71: tokio_threadpool::pool::Pool::spawn_thread::{{closure}}::h30de24531afb3e64 (0x564c21ab90b4)
             at /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.11/src/pool/mod.rs:346
  72: std::sys_common::backtrace::__rust_begin_short_backtrace::h16b42826f847934a (0x564c21ab2f0d)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/sys_common/backtrace.rs:135
  73: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hbf10a70e12f7089f (0x564c21a96991)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/thread/mod.rs:469
  74: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h926a68c32e549415 (0x564c21a6cce1)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/panic.rs:309
  75: std::panicking::try::do_call::h3818553f42ac30f6 (0x564c21a6ec9b)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/panicking.rs:297
  76: __rust_maybe_catch_panic (0x564c22063139)
             at src/libpanic_unwind/lib.rs:92
  77: std::panicking::try::h65c6c3f2fdeae71a (0x564c21a6ea55)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/panicking.rs:276
  78: std::panic::catch_unwind::h3a9ac77e73fe5f86 (0x564c21a6e971)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/panic.rs:388
  79: std::thread::Builder::spawn_unchecked::{{closure}}::h5912d2cd7bf2a7f5 (0x564c21a96775)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/libstd/thread/mod.rs:468
  80: <F as alloc::boxed::FnBox<A>>::call_box::hdb1ecfd1afe8eeb8 (0x564c21a9ac82)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/liballoc/boxed.rs:734
  81: call_once<(),()> (0x564c220624ed)
             at /rustc/852701ad6df90f4e4cdb11d487373f026f38e5b3/src/liballoc/boxed.rs:744
      start_thread
             at src/libstd/sys_common/thread.rs:14
      thread_start
             at src/libstd/sys/unix/thread.rs:81
  82: start_thread (0x7f3b3b0a86da)
  83: __clone (0x7f3b3abb988e)
  84: <unknown> (0x0)

Thread 'libp2p-0' panicked at 'assertion failed: list.is_connected()', /home/davidd/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-kad-0.4.0/src/behaviour.rs:351

This is a bug. Please report it at:

	https://github.com/paritytech/substrate/issues/new
```

**Comment by tomaka** [comment]
Considering that this issue only happened once in the history of Substrate, I'd say that it happens only in very obscure corner cases. Hopefully #994 and/or #996 fix it, but we obviously can't be sure.

**Comment by tomaka** [comment]
Considering that the panicking code no longer exists, I'll close this.
